-- TOP 10 CITIES CONTRIBUTING TO THE SALES OVER THE YEARS
SELECT CITY, SALES, RANK AS COUNTRY_RANK FROM (
        SELECT B.CITY,
           SUM (A.TOTAL_SALES) AS SALES,
          RANK () OVER( ORDER BY SUM(A.TOTAL_SALES) DESC) AS RANK 
          FROM SALES_FACT A,
               CITY_DIM B
         WHERE A.CITY_ID=B.CITY_ID 
         GROUP BY B.CITY ) 
 WHERE RANK <=10 ;

-- PRODUCTS CONTRIBUTING TO THE TOP 10% OF THE REVENUE
SELECT PRODUCT_NAME,SALES,"PERCENT RANK" AS PERCENTAGE  FROM (
    SELECT SUM (A.TOTAL_SALES) AS SALES,
  PERCENT_RANK () OVER( ORDER BY SUM(A.TOTAL_SALES) ) AS "PERCENT RANK",
               B.PRODUCT_NAME
          FROM SALES_FACT A,
               PRODUCT_DIM B
         WHERE A.PRODUCT_ID=B.PRODUCT_ID 
         GROUP BY B.PRODUCT_NAME )
 WHERE "PERCENT RANK" >= 0.9
 ORDER BY SALES DESC;
